php:
  image: php:7.0
  working_dir: /var/www
  volumes:
    - ./:/var/www

application:
  extends:
    php
  image: php:7-apache
  entrypoint: /var/www/opt/docker/development/entrypoint
  volumes:
    - ./opt/apache2/development/apache2.conf:/etc/apache2/apache2.conf
    - ./opt/apache2/development/virtual-host.conf:/etc/apache2/sites-enabled/virtual-host.conf
    - ./opt/php/development:/usr/local/etc/php/conf.d
  volumes_from:
    - application-cache-and-logs
  ports:
    - 10000:80

tests:
  extends:
    php
  entrypoint: /var/www/opt/docker/testing/entrypoint

application-cache-and-logs:
  image: busybox
  volumes:
    - /var/www/var/cache
    - /var/www/var/log

database:
  image: postgres
  environment:
    POSTGRES_PASSWORD: postgres

# #memcached:
# #  - image: memcached
